language: ruby
rvm:
  - 2.4.0
bundler_args: --without development
script:
  - bundle exec nanoc compile
  - bundle exec nanoc check internal_links mixed_content stale
cache:
  - bundler
after_success:
  - ./.travis_build_pages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  on:
    branch: master
